export const sub1 = [
  { id: 1, text: 'دستگاه اکسیژن ساز', url: '/pr' },
  { id: 2, text: 'کپسول اکسیژن', url: '/pr' },
  { id: 3, text: 'فشار سنج', url: '/pr' },
  { id: 4, text: 'فشارسنج عقربه ای', url: '/pr' },
  { id: 5, text: 'فشارسنج بازویی', url: '/pr' },
  { id: 6, text: 'فشارسنج مچی', url: '/pr' },
  { id: 7, text: 'ترازو', url: '/pr' },
  { id: 8, text: 'دستگاه ساکشن', url: '/pr' },
  { id: 9, text: 'ویلچر ساده', url: '/pr' },
  { id: 10, text: 'ویلچر برقی', url: '/pr' },
  { id: 11, text: 'بالابر بیمار', url: '/pr' },
  { id: 12, text: 'تشک مواج', url: '/pr' },
  { id: 13, text: 'تب سنج دیجیتال', url: '/pr' },
  { id: 14, text: 'دستگاه تست قند خون', url: '/pr' },
  { id: 15, text: 'دستگاه بخور و رطوبت ساز', url: '/pr' },
  { id: 16, text: 'ارتوپدی و توانبخشی', url: '/pr' },
  { id: 17, text: 'کیسه آب گرم و سرد', url: '/pr' },
  { id: 18, text: 'عصا', url: '/pr' },
  { id: 19, text: 'واکر', url: '/pr' },
  { id: 20, text: 'توالت فرنگی', url: '/pr' },
  { id: 21, text: 'دستگاه کمک تنفسی', url: '/pr' },
  { id: 22, text: 'بای پپ BIPAP', url: '/pr' },
  { id: 23, text: 'سی پپ CPAP', url: '/pr' },
  { id: 24, text: 'اسپیرومتری تنفسی', url: '/pr' },
  { id: 25, text: 'ماسک NIV کمک تنفسی', url: '/pr' },
  { id: 26, text: 'ونتیلاتور', url: '/pr' },
  { id: 27, text: 'آمبوبگ', url: '/pr' },
  { id: 28, text: 'دستگاه تصفیه هوا', url: '/pr' },
  { id: 29, text: 'گوشی پزشکی', url: '/pr' },
  { id: 30, text: 'نبولایزر', url: '/pr' },
  { id: 31, text: 'دستگاه فیزیوتراپی', url: '/pr' },
  { id: 32, text: 'لامپ مادون قرمز', url: '/pr' },
  { id: 33, text: 'ماساژور', url: '/pr' },
  { id: 34, text: 'صندلی ماساژور', url: '/pr' },
  { id: 35, text: 'روکش صندلی ماساژور', url: '/pr' },
  { id: 36, text: 'ماساژور پا', url: '/pr' },
  { id: 37, text: 'ماساژور بدن', url: '/pr' },
  { id: 38, text: 'ماساژور گردن و شانه', url: '/pr' },
  { id: 39, text: 'تشک برقی', url: '/pr' },
  { id: 40, text: 'بالش طبی', url: '/pr' },
  { id: 41, text: 'بالش طبی زیر سری', url: '/pr' },
  { id: 42, text: 'زیرنشیمنی', url: '/pr' },
  { id: 43, text: 'بالشت گردنی و گردنبند', url: '/pr' },
  { id: 44, text: 'پشت کمری', url: '/pr' },
  { id: 45, text: 'پالس اکسیمتری', url: '/pr' },
  { id: 46, text: 'شیردوش', url: '/pr' },
  { id: 47, text: 'نمایشگر ضربان قلب', url: '/pr' },
  { id: 48, text: 'تخت بیمارستانی', url: '/pr' },
  { id: 49, text: 'تخت و صندلی زیبایی', url: '/pr' },
  { id: 50, text: 'تخت معاینه', url: '/pr' },
  { id: 51, text: 'صندلی خونگیری', url: '/pr' },
  { id: 52, text: 'تخت ماساژ', url: '/pr' },
  { id: 53, text: 'تخت ژنیکولوژی و زنان', url: '/pr' },
  { id: 54, text: 'برانکارد', url: '/pr' },
  { id: 55, text: 'هتلینگ بیمار', url: '/pr' },
  { id: 56, text: 'ترالی بیمارستانی', url: '/pr' },
  { id: 57, text: 'کمد کنار بیمار', url: '/pr' },
  { id: 58, text: 'صندلی پزشکی', url: '/pr' },
  { id: 59, text: 'چراغ پزشکی', url: '/pr' },
  { id: 60, text: 'ست معاینه', url: '/pr' },
  { id: 61, text: 'اتوسکوپ', url: '/pr' },
  { id: 62, text: 'افتالموسکوپ', url: '/pr' },
  { id: 63, text: 'دستگاه نوار قلب', url: '/pr' },
  { id: 64, text: 'مانیتورینگ علائم حیاتی', url: '/pr' },
  { id: 65, text: 'ابزار جراحی', url: '/pr' },
  { id: 66, text: 'چکش پزشکی', url: '/pr' },
  { id: 67, text: 'هوک جراحی', url: '/pr' },
  { id: 68, text: 'استئوتوم', url: '/pr' },
  { id: 69, text: 'قیچی جراحی', url: '/pr' },
  { id: 70, text: 'بن کاتر و بن هولدر', url: '/pr' },
  { id: 71, text: 'پنست', url: '/pr' },
  { id: 72, text: 'اکارتور و رترکتور', url: '/pr' }
];