export const sub2 = [
  { id: 1, text: 'دستکش یکبار مصرف', url: '/pr' },
  { id: 2, text: 'دستکش نیتریل', url: '/pr' },
  { id: 3, text: 'دستکش لاتکس', url: '/pr' },
  { id: 4, text: 'دستکش وینیل', url: '/pr' },
  { id: 5, text: 'دستکش نایلونی', url: '/pr' },
  { id: 6, text: 'دستکش جراحی', url: '/pr' },
  { id: 7, text: 'ضدعفونی کننده', url: '/pr' },
  { id: 8, text: 'پد الکلی', url: '/pr' },
  { id: 9, text: 'بتادین', url: '/pr' },
  { id: 10, text: 'سیفتی باکس', url: '/pr' },
  { id: 11, text: 'آبسلانگ', url: '/pr' },
  { id: 12, text: 'ماسک پزشکی و بهداشتی', url: '/pr' },
  { id: 13, text: 'کیف امداد و کمک های اولیه', url: '/pr' },
  { id: 14, text: 'وسایل حجامت', url: '/pr' },
  { id: 15, text: 'تیغ جراحی', url: '/pr' },
  { id: 16, text: 'لیوان حجامت', url: '/pr' },
  { id: 17, text: 'وسایل پانسمان', url: '/pr' },
  { id: 18, text: 'باند سوختگی', url: '/pr' },
  { id: 19, text: 'باند کشی', url: '/pr' },
  { id: 20, text: 'باند زیر گچ ویبریل', url: '/pr' },
  { id: 21, text: 'باند گچی ارتوپدی', url: '/pr' },
  { id: 22, text: 'پد چشمی', url: '/pr' },
  { id: 23, text: 'پد پانسمان آماده', url: '/pr' },
  { id: 24, text: 'گاز طبی', url: '/pr' },
  { id: 25, text: 'باند کنار بافته', url: '/pr' },
  { id: 26, text: 'سوند', url: '/pr' },
  { id: 27, text: 'کیسه ادرار', url: '/pr' },
  { id: 28, text: 'کاندوم شیت', url: '/pr' },
  { id: 29, text: 'سوند فولی', url: '/pr' },
  { id: 30, text: 'سوند نلاتون', url: '/pr' },
  { id: 31, text: 'سوند معده', url: '/pr' },
  { id: 32, text: 'تزریقات', url: '/pr' },
  { id: 33, text: 'سرنگ و سرسوزن', url: '/pr' },
  { id: 34, text: 'سرنگ انسولین', url: '/pr' },
  { id: 35, text: 'آنژیوکت و اسکالپ وین', url: '/pr' },
  { id: 36, text: 'ست سرم و میکروست', url: '/pr' },
  { id: 37, text: 'پنبه بهداشتی', url: '/pr' },
  { id: 38, text: 'ساپورت های طبی', url: '/pr' },
  { id: 39, text: 'جوراب واریس', url: '/pr' },
  { id: 40, text: 'زانوبند', url: '/pr' },
  { id: 41, text: 'چسب پزشکی', url: '/pr' },
  { id: 42, text: 'چسب ضد حساسیت', url: '/pr' },
  { id: 43, text: 'چسب حصیری', url: '/pr' },
  { id: 44, text: 'چسب بخیه', url: '/pr' },
  { id: 45, text: 'چسب لکوپلاست', url: '/pr' },
  { id: 46, text: 'چسب زخم', url: '/pr' },
  { id: 47, text: 'چسب کمر', url: '/pr' },
  { id: 48, text: 'چسب آنژیوکت', url: '/pr' },
  { id: 49, text: 'ژل پزشکی', url: '/pr' },
  { id: 50, text: 'ژل لوبریکانت', url: '/pr' }
];
